In [72]:
import pandas as pd
import matplotlib.pyplot as plt

In [106]:
df = pd.read_csv('sample.csv' , index_col='id')
df.index.name = None

In [107]:
df.head()

    name  age         city   department  salary   join_date
1   John   28     New York  Engineering   85000  2021-03-15
2   Jane   32  Los Angeles    Marketing   78000  2020-08-01
3    Bob   45      Chicago        Sales   95000  2018-11-12
4  Alice   38      Houston           HR   72000  2019-05-20
5   Mike   50      Phoenix  Engineering  120000  2015-01-10

In [22]:
df.shape

(30, 6)

In [23]:
df[df['department'] == 'Engineering']

      name  age           city   department  salary   join_date
1     John   28       New York  Engineering   85000  2021-03-15
5     Mike   50        Phoenix  Engineering  120000  2015-01-10
7    David   41        Chicago  Engineering  110000  2017-04-18
10   Emily   31  San Francisco  Engineering  130000  2020-02-28
14  Sophia   33  San Francisco  Engineering  140000  2021-11-05
19  Daniel   42         Boston  Engineering  118000  2017-09-01
24  Harper   24        Phoenix  Engineering   75000  2023-07-01

In [24]:
df[df['salary'] > 100000]

         name  age           city   department  salary   join_date
5        Mike   50        Phoenix  Engineering  120000  2015-01-10
7       David   41        Chicago  Engineering  110000  2017-04-18
9       James   35         Boston      Finance  105000  2019-10-05
10      Emily   31  San Francisco  Engineering  130000  2020-02-28
14     Sophia   33  San Francisco  Engineering  140000  2021-11-05
17   Benjamin   48        Phoenix      Finance  115000  2014-06-15
19     Daniel   42         Boston  Engineering  118000  2017-09-01
25  Sebastian   37       New York      Finance  108000  2019-01-15
27       Jack   40  San Francisco        Sales  102000  2017-08-12

In [34]:
df[(df.age < 30) & (df.city == 'New York')]

      name  age      city   department  salary   join_date
1     John   28  New York  Engineering   85000  2021-03-15
6    Sarah   29  New York    Marketing   82000  2022-06-01
12  Olivia   27  New York           HR   68000  2022-09-12

In [46]:
df.sort_values(by='salary' , ascending=False)

,name,age,city,department,salary,join_date,dept_avg_salary
14,Sophia,33,San Francisco,Engineering,140000,2021-11-05,111142.857143
10,Emily,31,San Francisco,Engineering,130000,2020-02-28,111142.857143
5,Mike,50,Phoenix,Engineering,120000,2015-01-10,111142.857143
19,Daniel,42,Boston,Engineering,118000,2017-09-01,111142.857143
17,Benjamin,48,Phoenix,Finance,115000,2014-06-15,100000.000000
7,David,41,Chicago,Engineering,110000,2017-04-18,111142.857143
25,Sebastian,37,New York,Finance,108000,2019-01-15,100000.000000
9,James,35,Boston,Finance,105000,2019-10-05,100000.000000
27,Jack,40,San Francisco,Sales,102000,2017-08-12,84571.428571
13,William,36,Boston,Finance,98000,2018-03-30,100000.000000
3,Bob,45,Chicago,Sales,95000,2018-11-12,84571.428571
29,Samuel,35,Los Angeles,Finance,94000,2020-06-30,100000.000000
20,Amelia,34,San Francisco,Marketing,92000,2019-12-15,80400.000000
22,Evelyn,39,Los Angeles,Sales,91000,2018-05-05,84571.428571
11,Michael,44,Houston,Sales,89000,2016-07-22,84571.428571
18,Charlotte,30,New York,Sales,88000,2020-10-10,84571.428571
28,Elizabeth,43,Houston,HR,87000,2016-03-18,76600.000000
23,Alexander,46,Chicago,HR,85000,2015-11-20,76600.000000
1,John,28,New York,Engineering,85000,2021-03-15,111142.857143
6,Sarah,29,New York,Marketing,82000,2022-06-01,80400.000000
21,Henry,28,Houston,Finance,80000,2022-02-10,100000.000000
26,Abigail,31,Boston,Marketing,80000,2021-04-25,80400.000000
2,Jane,32,Los Angeles,Marketing,78000,2020-08-01,80400.000000
24,Harper,24,Phoenix,Engineering,75000,2023-07-01,111142.857143
4,Alice,38,Houston,HR,72000,2019-05-20,76600.000000
16,Mia,29,Los Angeles,HR,71000,2021-08-20,76600.000000
15,Liam,25,Chicago,Marketing,70000,2023-05-15,80400.000000
12,Olivia,27,New York,HR,68000,2022-09-12,76600.000000
30,Ella,26,Chicago,Sales,65000,2023-03-10,84571.428571
8,Emma,26,Los Angeles,Sales,62000,2023-01-15,84571.428571

In [43]:
df.groupby("department")['salary'].mean()

department
Engineering    111142.857143
Finance        100000.000000
HR              76600.000000
Marketing       80400.000000
Sales           84571.428571
Name: salary, dtype: float64

In [47]:
df.groupby('city').agg({'age' : ['max'] , 'salary' : ['min']})

              age salary
              max    min
city
Boston         42  80000
Chicago        46  65000
Houston        44  72000
Los Angeles    39  62000
New York       37  68000
Phoenix        50  75000
San Francisco  40  92000

In [52]:
df['join_date'] = pd.to_datetime(df['join_date'])
df

,name,age,city,department,salary,join_date,dept_avg_salary
1,John,28,New York,Engineering,85000,2021-03-15,111142.857143
2,Jane,32,Los Angeles,Marketing,78000,2020-08-01,80400.000000
3,Bob,45,Chicago,Sales,95000,2018-11-12,84571.428571
4,Alice,38,Houston,HR,72000,2019-05-20,76600.000000
5,Mike,50,Phoenix,Engineering,120000,2015-01-10,111142.857143
6,Sarah,29,New York,Marketing,82000,2022-06-01,80400.000000
7,David,41,Chicago,Engineering,110000,2017-04-18,111142.857143
8,Emma,26,Los Angeles,Sales,62000,2023-01-15,84571.428571
9,James,35,Boston,Finance,105000,2019-10-05,100000.000000
10,Emily,31,San Francisco,Engineering,130000,2020-02-28,111142.857143
11,Michael,44,Houston,Sales,89000,2016-07-22,84571.428571
12,Olivia,27,New York,HR,68000,2022-09-12,76600.000000
13,William,36,Boston,Finance,98000,2018-03-30,100000.000000
14,Sophia,33,San Francisco,Engineering,140000,2021-11-05,111142.857143
15,Liam,25,Chicago,Marketing,70000,2023-05-15,80400.000000
16,Mia,29,Los Angeles,HR,71000,2021-08-20,76600.000000
17,Benjamin,48,Phoenix,Finance,115000,2014-06-15,100000.000000
18,Charlotte,30,New York,Sales,88000,2020-10-10,84571.428571
19,Daniel,42,Boston,Engineering,118000,2017-09-01,111142.857143
20,Amelia,34,San Francisco,Marketing,92000,2019-12-15,80400.000000
21,Henry,28,Houston,Finance,80000,2022-02-10,100000.000000
22,Evelyn,39,Los Angeles,Sales,91000,2018-05-05,84571.428571
23,Alexander,46,Chicago,HR,85000,2015-11-20,76600.000000
24,Harper,24,Phoenix,Engineering,75000,2023-07-01,111142.857143
25,Sebastian,37,New York,Finance,108000,2019-01-15,100000.000000
26,Abigail,31,Boston,Marketing,80000,2021-04-25,80400.000000
27,Jack,40,San Francisco,Sales,102000,2017-08-12,84571.428571
28,Elizabeth,43,Houston,HR,87000,2016-03-18,76600.000000
29,Samuel,35,Los Angeles,Finance,94000,2020-06-30,100000.000000
30,Ella,26,Chicago,Sales,65000,2023-03-10,84571.428571

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 1 to 30
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             30 non-null     object
 1   age              30 non-null     int64
 2   city             30 non-null     object
 3   department       30 non-null     object
 4   salary           30 non-null     int64
 5   join_date        30 non-null     datetime64[ns]
 6   dept_avg_salary  30 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 1.9+ KB

In [60]:
df['join_year'] = df['join_date'].dt.year
df.head()

,name,age,city,department,salary,join_date,dept_avg_salary,join_year
1,John,28,New York,Engineering,85000,2021-03-15,111142.857143,2021
2,Jane,32,Los Angeles,Marketing,78000,2020-08-01,80400.000000,2020
3,Bob,45,Chicago,Sales,95000,2018-11-12,84571.428571,2018
4,Alice,38,Houston,HR,72000,2019-05-20,76600.000000,2019
5,Mike,50,Phoenix,Engineering,120000,2015-01-10,111142.857143,2015

In [63]:
emp_joined_each_year = df.groupby('join_year').size()
emp_joined_each_year

join_year
2014    1
2015    2
2016    2
2017    3
2018    3
2019    4
2020    4
2021    4
2022    3
2023    4
dtype: int64

In [108]:
import numpy as np
# Setting John's city to NaN and Emma's salary to NaN
df.loc[df['name'] == 'John', 'city'] = np.nan
df.loc[df['name'] == 'Emma', 'salary'] = np.nan

In [116]:
df.isnull().sum()

name          0
age           0
city          0
department    0
salary        0
join_date     0
dtype: int64

In [113]:
df.city.fillna("Unknown" , inplace= True)

In [119]:

df.salary.fillna(df.salary.mean())
df.head()

    name  age         city   department    salary   join_date
1   John   28      Unknown  Engineering   85000.0  2021-03-15
2   Jane   32  Los Angeles    Marketing   78000.0  2020-08-01
3    Bob   45      Chicago        Sales   95000.0  2018-11-12
4  Alice   38      Houston           HR   72000.0  2019-05-20
5   Mike   50      Phoenix  Engineering  120000.0  2015-01-10

In [122]:
name_with_J = df.name.str.startswith('J')
df[name_with_J]

     name  age           city   department    salary   join_date
1    John   28        Unknown  Engineering   85000.0  2021-03-15
2    Jane   32    Los Angeles    Marketing   78000.0  2020-08-01
9   James   35         Boston      Finance  105000.0  2019-10-05
27   Jack   40  San Francisco        Sales  102000.0  2017-08-12

In [127]:
df['capital_city'] = df['city'].str.upper()
df.head()

    name  age         city   department    salary   join_date capital_city
1   John   28      Unknown  Engineering   85000.0  2021-03-15      UNKNOWN
2   Jane   32  Los Angeles    Marketing   78000.0  2020-08-01  LOS ANGELES
3    Bob   45      Chicago        Sales   95000.0  2018-11-12      CHICAGO
4  Alice   38      Houston           HR   72000.0  2019-05-20      HOUSTON
5   Mike   50      Phoenix  Engineering  120000.0  2015-01-10      PHOENIX

In [130]:
df['salary_tier'] = df.salary.apply(lambda x : "Low" if x < 75000 else "Medium" if x <= 110000 else "High" )
df.head()

,name,age,city,department,salary,join_date,capital_city,salary_tier
1,John,28,Unknown,Engineering,85000.0,2021-03-15,UNKNOWN,Medium
2,Jane,32,Los Angeles,Marketing,78000.0,2020-08-01,LOS ANGELES,Medium
3,Bob,45,Chicago,Sales,95000.0,2018-11-12,CHICAGO,Medium
4,Alice,38,Houston,HR,72000.0,2019-05-20,HOUSTON,Low
5,Mike,50,Phoenix,Engineering,120000.0,2015-01-10,PHOENIX,High

In [132]:
manager_data = {
    'department': ['Engineering', 'Marketing', 'Sales', 'HR', 'Finance'],
    'manager': ['Sarah Conner', 'Tony Stark', 'Bruce Wayne', 'Peter Parker', 'Clark Kent']
}
df_managers = pd.DataFrame(manager_data)
df_managers

    department       manager
0  Engineering  Sarah Conner
1    Marketing    Tony Stark
2        Sales   Bruce Wayne
3           HR  Peter Parker
4      Finance    Clark Kent

In [140]:
df.merge(df_managers).head()

,name,age,city,department,salary,join_date,capital_city,salary_tier,manager
0,John,28,Unknown,Engineering,85000.0,2021-03-15,UNKNOWN,Medium,Sarah Conner
1,Jane,32,Los Angeles,Marketing,78000.0,2020-08-01,LOS ANGELES,Medium,Tony Stark
2,Bob,45,Chicago,Sales,95000.0,2018-11-12,CHICAGO,Medium,Bruce Wayne
3,Alice,38,Houston,HR,72000.0,2019-05-20,HOUSTON,Low,Peter Parker
4,Mike,50,Phoenix,Engineering,120000.0,2015-01-10,PHOENIX,High,Sarah Conner

# Titanic-dataset

In [142]:
df = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")

In [143]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [144]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [145]:
df.Age.fillna(df.Age.mean() , inplace= True)

/tmp/ipykernel_170345/3206175955.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Age.fillna(df.Age.mean() , inplace= True)

In [147]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [148]:
df.Cabin

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ...
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: object

In [94]:
df.Cabin.value_counts()

Cabin
G6             4
C23 C25 C27    4
B96 B98        4
F2             3
D              3
              ..
E17            1
A24            1
C50            1
B42            1
C148           1
Name: count, Length: 147, dtype: int64

In [149]:
df.dropna(subset=['Embarked'] , inplace=True)

In [150]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

In [151]:
df.Cabin.fillna("Unknown", inplace=True)

/tmp/ipykernel_170345/3890994056.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Cabin.fillna("Unknown", inplace=True)

In [152]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [154]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Unknown,S

In [157]:
df.Survived.describe()

count    889.000000
mean       0.382452
std        0.486260
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        1.000000
Name: Survived, dtype: float64

In [158]:
df.Sex.value_counts()

Sex
male      577
female    312
Name: count, dtype: int64

In [163]:
df['Survived'].groupby(df.Sex).mean()

Sex
female    0.740385
male      0.188908
Name: Survived, dtype: float64

In [165]:
df.Survived.groupby(df.Pclass).mean()

Pclass
1    0.626168
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [183]:
oldest_surviour = df[(df.Survived == 1)]
oldest_surviour.Age.max()
oldest_surviour.sort_values(by='Age' , ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.00,0,0,27042,30.0000,A23,S
275,276,1,1,"Andrews, Miss Kornelia Theodosia",female,63.00,1,0,13502,77.9583,D7,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.00,0,0,4134,9.5875,Unknown,S
570,571,1,2,"Harris, Mr. George",male,62.00,0,0,S.W./PP 752,10.5000,Unknown,S
366,367,1,1,"Warren, Mrs. Frank Manley (Anna Sophia Atkinson)",female,60.00,1,0,110813,75.2500,D37,C
...,...,...,...,...,...,...,...,...,...,...,...,...
831,832,1,2,"Richards, Master George Sibley",male,0.83,1,1,29106,18.7500,Unknown,S
469,470,1,3,"Baclini, Miss Helene Barbara",female,0.75,2,1,2666,19.2583,Unknown,C
644,645,1,3,"Baclini, Miss Eugenie",female,0.75,2,1,2666,19.2583,Unknown,C
755,756,1,2,"Hamalainen, Master Viljo",male,0.67,1,1,250649,14.5000,Unknown,S
803,804,1,3,"Thomas, Master Assad Alexander",male,0.42,0,1,2625,8.5167,Unknown,C

In [190]:
children_df = df[df.Age < 18]
children_df.Age.count()

np.int64(113)

In [203]:
children_df.Survived.value_counts()

Survived
1    61
0    52
Name: count, dtype: int64

In [204]:
children_df.Survived.mean()
child_survived = children_df[children_df.Survived == 1]
child_survived.Survived.count()
children_df.groupby(df.Survived).Survived.count()

Survived
0    52
1    61
Name: Survived, dtype: int64

In [208]:
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df.FamilySize.describe()

count    889.000000
mean       1.906637
std        1.614703
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max       11.000000
Name: FamilySize, dtype: float64

In [210]:
avg_family_size_survived = df[df.Survived == 1].FamilySize.mean()
avg_family_size_survived

np.float64(1.9441176470588235)

In [211]:
avg_family_size_survived = df[df.Survived == 0].FamilySize.mean()
avg_family_size_survived

np.float64(1.883424408014572)

In [212]:
df.groupby(df.Survived).FamilySize.mean()

Survived
0    1.883424
1    1.944118
Name: FamilySize, dtype: float64

In [214]:
df.groupby(['Pclass' , 'Sex']).Survived.mean()

Pclass  Sex
1       female    0.967391
        male      0.368852
2       female    0.921053
        male      0.157407
3       female    0.500000
        male      0.135447
Name: Survived, dtype: float64

In [217]:
df.groupby(['Pclass' , 'Sex']).agg({'Fare' : ['mean' , 'size'] ,})

                     Fare
                     mean size
Pclass Sex
1      female  106.693750   92
       male     67.226127  122
2      female   21.970121   76
       male     19.741782  108
3      female   16.118810  144
       male     12.661633  347